version: '3'
services:
  eureka-server:
    image: openjdk:8
    container_name: eureka-server
    hostname: eureka-server
    ports:
      - "8761:8761"
    volumes:
      - ./eureka/target:/var/jars
    command: java -jar /var/jars/eureka-0.0.1-SNAPSHOT.jar
  #eureka-server:
   # image: springcloud/eureka
    #hostname: eureka-server
    #volumes:
    #  - ./tmp:/tmp
    #ports:
    #  - "8761:8761"
  micros_spring_app_a:
    image: openjdk:8
    container_name: micros_spring_app_a
    ports:
      - "8081:8081"
    volumes:
      - ./spring-app-a/target:/var/jars
    command: java -jar /var/jars/spring-app-a-0.0.1-SNAPSHOT.jar
    links:
      - eureka-server
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
  micros_spring_app_b:
    image: openjdk:8
    container_name: micros_spring_app_b
    ports:
      - "8082:8082"
    volumes:
      - ./spring-app-b/target:/var/jars
    command: java -jar /var/jars/spring-app-b-0.0.1-SNAPSHOT.jar
    links:
      - eureka-server
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka