version: '3'
services:
  eureka-server:
    image: openjdk:8
    container_name: eureka-server
    ports:
      - "8761:8761"
    volumes:
      - ./eureka/target:/var/jars
    command: java -jar /var/jars/eureka-0.0.1-SNAPSHOT.jar
  zipkin-server:
    image: openjdk:8
    container_name: zipkin-server
    ports:
      - "9411:9411"
    volumes:
      - ./zipkin:/var/jars
    command: java -jar /var/jars/zipkin-server-2.23.4-exec.jar
  boot-admin:
    image: openjdk:8
    container_name: boot-admin
    ports:
      - "8085:8085"
    volumes:
      - ./spring-boot-admin/target:/var/jars
    command: java -jar /var/jars/bootadmin-0.0.1-SNAPSHOT.jar
  gateway:
    image: openjdk:8
    container_name: gateway
    ports:
      - "8080:8080"
    volumes:
      - ./gateway/target:/var/jars
    command: java -jar /var/jars/gateway-0.0.1-SNAPSHOT.jar
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
      ZIPKIN_URI: http://zipkin-server:9411
      SPRING_BOOT_ADMIN_URI: http://boot-admin:8085
    links:
      - eureka-server
      - zipkin-server
      - boot-admin
  cafe-app:
    image: openjdk:8
    container_name: cafe-app
    ports:
      - "8081:8081"
    volumes:
      - ./cafe/target:/var/jars
    command: java -jar /var/jars/cafe-0.0.1-SNAPSHOT.jar
    links:
      - eureka-server
      - zipkin-server
      - boot-admin
      - gateway
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
      ZIPKIN_URI: http://zipkin-server:9411
      SPRING_BOOT_ADMIN_URI: http://boot-admin:8085
  kitchen-app:
    image: openjdk:8
    container_name: kitchen-app
    ports:
      - "8082:8082"
    volumes:
      - ./kitchen/target:/var/jars
    command: java -jar /var/jars/kitchen-0.0.1-SNAPSHOT.jar
    links:
      - eureka-server
      - zipkin-server
      - boot-admin
      - gateway
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
      ZIPKIN_URI: http://zipkin-server:9411
      SPRING_BOOT_ADMIN_URI: http://boot-admin:8085
      RESPONSE_DELAY: 1000
      INSTANCE_NAME: fast_cat
  kitchen-app-2:
    image: openjdk:8
    container_name: skitchen-app-2
    volumes:
      - ./kitchen/target:/var/jars
    command: java -jar /var/jars/kitchen-0.0.1-SNAPSHOT.jar
    links:
      - eureka-server
      - zipkin-server
      - boot-admin
      - gateway
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
      ZIPKIN_URI: http://zipkin-server:9411
      SPRING_BOOT_ADMIN_URI: http://boot-admin:8085
      RESPONSE_DELAY: 3000
      INSTANCE_NAME: slow_dog
  steward-app:
    image: openjdk:8
    container_name: steward-app
    ports:
      - "8083:8083"
    volumes:
      - ./steward/target:/var/jars
    command: java -jar /var/jars/steward-0.0.1-SNAPSHOT.jar
    links:
      - eureka-server
      - zipkin-server
      - boot-admin
      - gateway
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
      ZIPKIN_URI: http://zipkin-server:9411
      SPRING_BOOT_ADMIN_URI: http://boot-admin:8085