version: '3'
services:
  eureka-server:
    image: openjdk:8
    container_name: eureka-server
    ports:
      - "8761:8761"
    volumes:
      - ./eureka/target:/var/jars
    command: java -jar /var/jars/eureka-0.0.1-SNAPSHOT.jar
  spring-app-a:
    image: openjdk:8
    container_name: spring-app-a
    ports:
      - "8081:8081"
    volumes:
      - ./spring-app-a/target:/var/jars
    command: java -jar /var/jars/spring-app-a-0.0.1-SNAPSHOT.jar
    links:
      - eureka-server
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
      SPRING_APP_B_HOST: spring-app-b
  spring-app-b:
    image: openjdk:8
    container_name: spring-app-b
    ports:
      - "8082:8082"
    volumes:
      - ./spring-app-b/target:/var/jars
    command: java -jar /var/jars/spring-app-b-0.0.1-SNAPSHOT.jar
    links:
      - eureka-server
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka